import os
from flask import Flask, render_template, request, jsonify, send_file
from groq import Groq
from reportlab.pdfgen import canvas


app = Flask(__name__)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


@app.route('/')
def home():
    return render_template('index.html')

@app.route('/generate-testcases', methods=['POST'])
def generate_testcases():
    data = request.json
    module = data.get('module', '')
    fields = data.get('fields', '')
    prompt = f"""Act as a senior QA analyst with 10 years experience.
Generate 10 professional test cases for {module} page with these fields: {fields}
Format each test case as:
TC ID | Title | Steps | Expected Result | Priority | Severity
Include positive, negative and boundary test cases."""
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )
    return jsonify({"result": response.choices[0].message.content})

@app.route('/generate-bugreport', methods=['POST'])
def generate_bugreport():
    data = request.json
    description = data.get('description', '')
    module = data.get('module', '')
    prompt = f"""Act as a senior QA analyst.
Write a professional bug report for this issue in {module} module:
{description}
Include: Bug ID, Title, Module, Severity, Priority,
Steps to Reproduce, Expected Result, Actual Result, Environment details.
Make it ready to log in Jira."""
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )
    return jsonify({"result": response.choices[0].message.content})

@app.route('/generate-testdata', methods=['POST'])
def generate_testdata():
    data = request.json
    field_type = data.get('field_type', '')
    prompt = f"""Act as a senior QA analyst.
Generate 10 sets of test data for {field_type} field.
Include 5 valid and 5 invalid data sets.
Include boundary values and special characters.
Format as a clear table."""
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )
    return jsonify({"result": response.choices[0].message.content})

@app.route('/download-pdf')
def download_pdf():
    file_name = "QA_Report.pdf"
    c = canvas.Canvas(file_name)
    c.drawString(100, 800, "AI QA Assistant Report")
    c.drawString(100, 770, "Generated by Sarbani Mondal")
    c.save()
    return send_file(file_name, as_attachment=True)

if __name__ == '__main__':
    app.run(debug=True)