import os
from flask import Flask, render_template, request, jsonify, send_file
from groq import Groq
from reportlab.pdfgen import canvas

app = Flask(__name__)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


@app.route('/')
def home():
    return render_template('index.html')

@app.route('/generate-testcases', methods=['POST'])
def generate_testcases():
    data = request.json
    module = data.get('module', '')
    fields = data.get('fields', '')
    prompt = f"""Act as a senior QA analyst with 10 years experience.
Generate 10 professional test cases for {module} page with these fields: {fields}
Format each test case as:
TC ID | Title | Steps | Expected Result | Priority | Severity
Include positive, negative and boundary test cases."""
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )
    return jsonify({"result": response.choices[0].message.content})

@app.route('/generate-bugreport', methods=['POST'])
def generate_bugreport():
    data = request.json
    description = data.get('description', '')
    module = data.get('module', '')
    prompt = f"""Act as a senior QA analyst.
Write a professional bug report for this issue in {module} module:
{description}
Include: Bug ID, Title, Module, Severity, Priority,
Steps to Reproduce, Expected Result, Actual Result, Environment details.
Make it ready to log in Jira."""
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )
    return jsonify({"result": response.choices[0].message.content})

@app.route('/generate-testdata', methods=['POST'])
def generate_testdata():
    data = request.json
    field_type = data.get('field_type', '')
    prompt = f"""Act as a senior QA analyst.
Generate 10 sets of test data for {field_type} field.
Include 5 valid and 5 invalid data sets.
Include boundary values and special characters.
Format as a clear table."""
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": prompt}]
    )
    return jsonify({"result": response.choices[0].message.content})

@app.route('/download-pdf')
def download_pdf():
    file_name = "QA_Report.pdf"
    c = canvas.Canvas(file_name)
    c.drawString(100, 800, "AI QA Assistant Report")
    c.drawString(100, 770, "Generated by Sarbani Mondal")
    c.save()
    return send_file(file_name, as_attachment=True)

@app.route('/download-excel', methods=['POST'])
def download_excel():
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment
    
    data = request.json
    content = data.get('content', '')
    
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Test Cases"
    
    # Header row
    headers = ['TC ID', 'Title', 'Steps', 'Expected Result', 'Priority', 'Severity']
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="1A5276", end_color="1A5276", fill_type="solid")
        cell.alignment = Alignment(horizontal='center')
    
    # Parse and add content rows
    lines = content.strip().split('\n')
    row = 2
    for line in lines:
        if line.strip():
            ws.cell(row=row, column=1, value=line.strip())
            row += 1
    
    # Auto width
    for col in ws.columns:
        max_length = 0
        for cell in col:
            if cell.value:
                max_length = max(max_length, len(str(cell.value)))
        ws.column_dimensions[col[0].column_letter].width = min(max_length + 5, 50)
    
    file_name = "QA_Test_Cases.xlsx"
    wb.save(file_name)
    return send_file(file_name, as_attachment=True)

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port, debug=False)